kind: pipeline
name: production
steps:
- name: docker  
  image: plugins/docker:17.12
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: vwxyzjn/portwarden-server-prod
    dockerfile: Dockerfile.Build
    auto_tag: true
    target: production
    salt:
      from_secret: Salt
    build_args:
      - Salt=$PLUGIN_SALT
    debug: true
