version: '3'

services:

  scheduler:
    image: vwxyzjn/portwarden-scheduler:0.0.1
    stdin_open: true
    tty: true
    depends_on:
      - redis
    ports:
      - 5000:5000
    volumes:
      - .:/go/src/github.com/vwxyzjn/portwarden

  redis:
    image: redis
    ports:
      - 6379:6379

  worker:
    image: vwxyzjn/portwarden-scheduler:0.0.1
    stdin_open: true
    tty: true
    depends_on:
      - redis
    volumes:
      - .:/go/src/github.com/vwxyzjn/portwarden
