version: '3'

services:

  scheduler:
    image: vwxyzjn/portwarden-server-dev:1.7.0
    stdin_open: true
    tty: true
    environment:
      - BITWARDENCLI_APPDATA_DIR=/BitwardenCLI
      - BackupDefaultSleepMilliseconds=20
    depends_on:
      - redis
    ports:
      - 5000:5000
    volumes:
      - .:/go/src/github.com/vwxyzjn/portwarden
    working_dir:
      /go/src/github.com/vwxyzjn/portwarden/web/scheduler
    # command:
    #   go run main.go

  redis:
    image: redis
    ports:
      - 6379:6379

  worker:
    image: vwxyzjn/portwarden-server-dev:1.7.0
    stdin_open: true
    tty: true
    environment:
      - BITWARDENCLI_APPDATA_DIR=/BitwardenCLI
      - BackupDefaultSleepMilliseconds=20
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - .:/go/src/github.com/vwxyzjn/portwarden
    working_dir:
      /go/src/github.com/vwxyzjn/portwarden/web/worker
    command:
      go run main.go

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"

  frontend:
    image: vwxyzjn/portwarden-frontend:1.2.0
    restart: always
    ports:
    - "8000:8000"
