apiVersion: v1
kind: Namespace
metadata: 
  name: portwarden


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: portwarden
  name: portwarden-scheduler
  labels:
    app: portwarden-scheduler
spec:
  selector:
    matchLabels:
      app: portwarden-scheduler
      tier: backend
  # replicas: 7
  template:
    metadata:
      labels:
        app: portwarden-scheduler
        tier: backend
    spec:
      containers:
        - name: portwarden-scheduler
          image: vwxyzjn/portwarden-scheduler:0.0.1
          ports:
            - name: http
              containerPort: 5000
          stdin: true
          tty: true
# # START of dev related lines, local mount doesn't work on windows
#           volumeMounts:
#           - mountPath: /go/src/github.com/vwxyzjn/portwarden
#             name: dev-volume
#       volumes:
#       - name: dev-volume
#         hostPath:
#           path: /data
# # END of dev related lines
---
kind: Service
apiVersion: v1
metadata:
  namespace: portwarden
  name: portwarden-scheduler
spec:
  selector:
    app: portwarden-scheduler
    tier: backend
  ports:
  - port: 5000
    targetPort: 5000


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: portwarden
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
      tier: backend
  template:
    metadata:
      labels:
        app: redis
        tier: backend
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
---
kind: Service
apiVersion: v1
metadata:
  namespace: portwarden
  name: redis
spec:
  selector:
    app: redis
    tier: backend
  ports:
  - port: 6379
    targetPort: 6379
